//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoaSisProduccionReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/", ConfigurationName="SoaSisProduccionReference.registroFuaBatch")]
    public interface registroFuaBatch
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrarFuaPublico no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/registrarFuaPublico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoaSisProduccionReference.registrarFuaResponse1 registrarFuaPublico(SoaSisProduccionReference.registrarFuaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/registrarFuaPublico", ReplyAction="*")]
        System.Threading.Tasks.Task<SoaSisProduccionReference.registrarFuaResponse1> registrarFuaPublicoAsync(SoaSisProduccionReference.registrarFuaRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarPaquete no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/consultarPaquete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoaSisProduccionReference.consultarPaqueteResponse1 consultarPaquete(SoaSisProduccionReference.consultarPaqueteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/consultarPaquete", ReplyAction="*")]
        System.Threading.Tasks.Task<SoaSisProduccionReference.consultarPaqueteResponse1> consultarPaqueteAsync(SoaSisProduccionReference.consultarPaqueteRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
    public partial class requestHeader
    {
        
        private string canalField;
        
        private string usuarioField;
        
        private string autorizacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string canal
        {
            get
            {
                return this.canalField;
            }
            set
            {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string autorizacion
        {
            get
            {
                return this.autorizacionField;
            }
            set
            {
                this.autorizacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
    public partial class Observacion
    {
        
        private string fuaField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fua
        {
            get
            {
                return this.fuaField;
            }
            set
            {
                this.fuaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
    public partial class registrarFuaRequest
    {
        
        private string nombreZipField;
        
        private byte[] dataZipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreZip
        {
            get
            {
                return this.nombreZipField;
            }
            set
            {
                this.nombreZipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] dataZip
        {
            get
            {
                return this.dataZipField;
            }
            set
            {
                this.dataZipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
    public partial class registrarFuaResponse
    {
        
        private string codigoField;
        
        private string respuestaField;
        
        private string paqueteNombreField;
        
        private string paqueteIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string paqueteNombre
        {
            get
            {
                return this.paqueteNombreField;
            }
            set
            {
                this.paqueteNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string paqueteId
        {
            get
            {
                return this.paqueteIdField;
            }
            set
            {
                this.paqueteIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarFuaRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
        public SoaSisProduccionReference.requestHeader requestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/", Order=0)]
        public SoaSisProduccionReference.registrarFuaRequest registrarFuaRequest;
        
        public registrarFuaRequest1()
        {
        }
        
        public registrarFuaRequest1(SoaSisProduccionReference.requestHeader requestHeader, SoaSisProduccionReference.registrarFuaRequest registrarFuaRequest)
        {
            this.requestHeader = requestHeader;
            this.registrarFuaRequest = registrarFuaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarFuaResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/", Order=0)]
        public SoaSisProduccionReference.registrarFuaResponse registrarFuaResponse;
        
        public registrarFuaResponse1()
        {
        }
        
        public registrarFuaResponse1(SoaSisProduccionReference.registrarFuaResponse registrarFuaResponse)
        {
            this.registrarFuaResponse = registrarFuaResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
    public partial class consultarPaqueteRequest
    {
        
        private string paqueteNombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string paqueteNombre
        {
            get
            {
                return this.paqueteNombreField;
            }
            set
            {
                this.paqueteNombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
    public partial class consultarPaqueteResponse
    {
        
        private string paqueteEstadoField;
        
        private string pasoDescripcionField;
        
        private string pasoEstadoField;
        
        private long ateCargadasField;
        
        private long ateDuplicadasField;
        
        private long ateConsolidadasField;
        
        private long ateObservadasField;
        
        private long ateProduccionField;
        
        private Observacion[] observacionesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string paqueteEstado
        {
            get
            {
                return this.paqueteEstadoField;
            }
            set
            {
                this.paqueteEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pasoDescripcion
        {
            get
            {
                return this.pasoDescripcionField;
            }
            set
            {
                this.pasoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string pasoEstado
        {
            get
            {
                return this.pasoEstadoField;
            }
            set
            {
                this.pasoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long ateCargadas
        {
            get
            {
                return this.ateCargadasField;
            }
            set
            {
                this.ateCargadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long ateDuplicadas
        {
            get
            {
                return this.ateDuplicadasField;
            }
            set
            {
                this.ateDuplicadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long ateConsolidadas
        {
            get
            {
                return this.ateConsolidadasField;
            }
            set
            {
                this.ateConsolidadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long ateObservadas
        {
            get
            {
                return this.ateObservadasField;
            }
            set
            {
                this.ateObservadasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long ateProduccion
        {
            get
            {
                return this.ateProduccionField;
            }
            set
            {
                this.ateProduccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("observaciones", IsNullable=true, Order=8)]
        public Observacion[] observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPaqueteRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/")]
        public SoaSisProduccionReference.requestHeader requestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/", Order=0)]
        public SoaSisProduccionReference.consultarPaqueteRequest consultarPaqueteRequest;
        
        public consultarPaqueteRequest1()
        {
        }
        
        public consultarPaqueteRequest1(SoaSisProduccionReference.requestHeader requestHeader, SoaSisProduccionReference.consultarPaqueteRequest consultarPaqueteRequest)
        {
            this.requestHeader = requestHeader;
            this.consultarPaqueteRequest = consultarPaqueteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPaqueteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sis.gob.pe/esb/negocio/registroFuaBatch/v2/", Order=0)]
        public SoaSisProduccionReference.consultarPaqueteResponse consultarPaqueteResponse;
        
        public consultarPaqueteResponse1()
        {
        }
        
        public consultarPaqueteResponse1(SoaSisProduccionReference.consultarPaqueteResponse consultarPaqueteResponse)
        {
            this.consultarPaqueteResponse = consultarPaqueteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface registroFuaBatchChannel : SoaSisProduccionReference.registroFuaBatch, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class registroFuaBatchClient : System.ServiceModel.ClientBase<SoaSisProduccionReference.registroFuaBatch>, SoaSisProduccionReference.registroFuaBatch
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public registroFuaBatchClient() : 
                base(registroFuaBatchClient.GetDefaultBinding(), registroFuaBatchClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.registroFuaBatchSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public registroFuaBatchClient(EndpointConfiguration endpointConfiguration) : 
                base(registroFuaBatchClient.GetBindingForEndpoint(endpointConfiguration), registroFuaBatchClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public registroFuaBatchClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(registroFuaBatchClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public registroFuaBatchClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(registroFuaBatchClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public registroFuaBatchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoaSisProduccionReference.registrarFuaResponse1 SoaSisProduccionReference.registroFuaBatch.registrarFuaPublico(SoaSisProduccionReference.registrarFuaRequest1 request)
        {
            return base.Channel.registrarFuaPublico(request);
        }
        
        public SoaSisProduccionReference.registrarFuaResponse registrarFuaPublico(SoaSisProduccionReference.requestHeader requestHeader, SoaSisProduccionReference.registrarFuaRequest registrarFuaRequest)
        {
            SoaSisProduccionReference.registrarFuaRequest1 inValue = new SoaSisProduccionReference.registrarFuaRequest1();
            inValue.requestHeader = requestHeader;
            inValue.registrarFuaRequest = registrarFuaRequest;
            SoaSisProduccionReference.registrarFuaResponse1 retVal = ((SoaSisProduccionReference.registroFuaBatch)(this)).registrarFuaPublico(inValue);
            return retVal.registrarFuaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoaSisProduccionReference.registrarFuaResponse1> SoaSisProduccionReference.registroFuaBatch.registrarFuaPublicoAsync(SoaSisProduccionReference.registrarFuaRequest1 request)
        {
            return base.Channel.registrarFuaPublicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoaSisProduccionReference.registrarFuaResponse1> registrarFuaPublicoAsync(SoaSisProduccionReference.requestHeader requestHeader, SoaSisProduccionReference.registrarFuaRequest registrarFuaRequest)
        {
            SoaSisProduccionReference.registrarFuaRequest1 inValue = new SoaSisProduccionReference.registrarFuaRequest1();
            inValue.requestHeader = requestHeader;
            inValue.registrarFuaRequest = registrarFuaRequest;
            return ((SoaSisProduccionReference.registroFuaBatch)(this)).registrarFuaPublicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoaSisProduccionReference.consultarPaqueteResponse1 SoaSisProduccionReference.registroFuaBatch.consultarPaquete(SoaSisProduccionReference.consultarPaqueteRequest1 request)
        {
            return base.Channel.consultarPaquete(request);
        }
        
        public SoaSisProduccionReference.consultarPaqueteResponse consultarPaquete(SoaSisProduccionReference.requestHeader requestHeader, SoaSisProduccionReference.consultarPaqueteRequest consultarPaqueteRequest)
        {
            SoaSisProduccionReference.consultarPaqueteRequest1 inValue = new SoaSisProduccionReference.consultarPaqueteRequest1();
            inValue.requestHeader = requestHeader;
            inValue.consultarPaqueteRequest = consultarPaqueteRequest;
            SoaSisProduccionReference.consultarPaqueteResponse1 retVal = ((SoaSisProduccionReference.registroFuaBatch)(this)).consultarPaquete(inValue);
            return retVal.consultarPaqueteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoaSisProduccionReference.consultarPaqueteResponse1> SoaSisProduccionReference.registroFuaBatch.consultarPaqueteAsync(SoaSisProduccionReference.consultarPaqueteRequest1 request)
        {
            return base.Channel.consultarPaqueteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoaSisProduccionReference.consultarPaqueteResponse1> consultarPaqueteAsync(SoaSisProduccionReference.requestHeader requestHeader, SoaSisProduccionReference.consultarPaqueteRequest consultarPaqueteRequest)
        {
            SoaSisProduccionReference.consultarPaqueteRequest1 inValue = new SoaSisProduccionReference.consultarPaqueteRequest1();
            inValue.requestHeader = requestHeader;
            inValue.consultarPaqueteRequest = consultarPaqueteRequest;
            return ((SoaSisProduccionReference.registroFuaBatch)(this)).consultarPaqueteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        new public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.registroFuaBatchSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.registroFuaBatchSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://ws01.sis.gob.pe/cxf/esb/negocio/registroFuaBatch/v2/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return registroFuaBatchClient.GetBindingForEndpoint(EndpointConfiguration.registroFuaBatchSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return registroFuaBatchClient.GetEndpointAddress(EndpointConfiguration.registroFuaBatchSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            registroFuaBatchSoap,
        }
    }
}
