namespace WebAppMaternidad.CapaEntidades
{
    public class EcoCardiotografia
    {
        public int Id { get; set; }
        public int? IdMovimiento { get; set; }
        public int? IdOrden { get; set; }
        public int? IdProducto { get; set; }
        public int? IdRealizaPrueba { get; set; }
        public int? IdMedicoRevisa { get; set; }
        public string FechaResultado { get; set; }
        public string FUR { get; set; }
        public string FPP { get; set; }
        public string AU { get; set; }
        public string TA { get; set; }
        public string Gesta { get; set; }
        public string PARA1 { get; set; }
        public string PARA2 { get; set; }
        public string PARA3 { get; set; }
        public string PARA4 { get; set; }
        public string EGFURsem { get; set; }
        public string EGFURdias { get; set; }
        public string EGXECOsem { get; set; }
        public string EGXECOdias { get; set; }
        public string PA { get; set; }
        public string FC { get; set; }
        public string T { get; set; }
        public int? IdMedicacionPrevia { get; set; }
        public string DMedicacionPrevia { get; set; }
        public int? BienestarFetal { get; set; }
        public int? Preeclampsia { get; set; }
        public int? InsuficienciaPlacentaria { get; set; }
        public int? Diabetes { get; set; }
        public int? CordonNucal { get; set; }
        public int? IdCordonNucal { get; set; }
        public int? EmbarazoMultiple { get; set; }
        public int? HTAcron { get; set; }
        public int? Postermino { get; set; }
        public int? Obesidad { get; set; }
        public int? PlacentaPrevia { get; set; }
        public int? RPM { get; set; }
        public int? HipGest { get; set; }
        public int? RCIU { get; set; }
        public int? Colestasis { get; set; }
        public int? Oligoamn { get; set; }
        public int? MovDism { get; set; }
        public int? AnemiaFetal { get; set; }
        public int? AnemiaMat { get; set; }
        public int? Poliamni { get; set; }
        public int? Contraccion { get; set; }
        public int? Malformacion { get; set; }
        public int? ITU { get; set; }
        public int? ILA { get; set; }
        public string DILA { get; set; }
        public int? APP { get; set; }
        public int? Otro { get; set; }
        public string DOtro { get; set; }
        public int? Hemorragia { get; set; }
        public string AUdop { get; set; }
        public string ACMdop { get; set; }
        public string RCPdop { get; set; }
        public string IAdop { get; set; }
        public string DVdop { get; set; }
        public int? PrimeraVez { get; set; }
        public int? Control { get; set; }
        public int? Posseiro { get; set; }
        public int? SindromeVenaCava { get; set; }
        public string ObservacionesNST { get; set; }
        public int? Oxitocina { get; set; }
        public string DOxitocina { get; set; }
        public int? EstimuloMamario { get; set; }
        public string DEstimuloMamario { get; set; }
        public string MonitoreoHoraInicio { get; set; }
        public string MonitoreoHoraTermino { get; set; }
        public string MonitoreoTotal { get; set; }
        public int? ValoracionLineaBase { get; set; }
        public int? ValoracionVariabilidad { get; set; }
        public int? ValoracionAceleraciones { get; set; }
        public int? ValoracionDesaceleraciones { get; set; }
        public int? ValoracionMovimientosCorporales { get; set; }
        public int? ValoracionTotal { get; set; }
        public int? Negativo { get; set; }
        public int? Insatisfactorio { get; set; }
        public int? ConReactividad { get; set; }
        public int? Positivo { get; set; }
        public int? Equivoco { get; set; }
        public int? SinReactividad { get; set; }
        public int? Sospechosos { get; set; }
        public bool? Normal { get; set; }
        public bool? Atipico { get; set; }
        public bool? Patologico { get; set; }
        public string Observaciones { get; set; }
        public string RecomendacionRepetir { get; set; }
        public string RecomendacionInduccion { get; set; }
        public string RecomendacionCST { get; set; }
        public string RecomendacionOtros { get; set; }
        public int? IdTipoEdadGestacional { get; set; }
        public string EGsem { get; set; }
        public string EGdias { get; set; }
    }
}
