namespace WebAppMaternidad.CapaEntidades
{
    public class EcoCardiografia
    {
        public int Id { get; set; }
        public int? NumeroFeto { get; set; }
        public int? Presentacion { get; set; }
        public string Dbp { get; set; }
        public string Cc { get; set; }
        public string Ca { get; set; }
        public string Lf { get; set; }
        public string Lh { get; set; }
        public string Peso { get; set; }
        public int? Sexo { get; set; }
        public string EdadGestacional { get; set; }
        public int? Placenta { get; set; }
        public int? Grado { get; set; }
        public int? Cordon { get; set; }
        public string ILA { get; set; }
        public string IpUterinaDerecha { get; set; }
        public string IpUterinaIzquierda { get; set; }
        public string UterinasIpMedio { get; set; }
        public string UterinaPerc { get; set; }
        public string UterinaMom { get; set; }
        public string Observaciones { get; set; }
        public string Conclusion { get; set; }
        public string Sugerencia { get; set; }
        public string Fecha { get; set; }
        public int? IdProducto { get; set; }
        public int? IdOrden { get; set; }
        public int? IdRealizaPrueba { get; set; }
        public int? IdMovimiento { get; set; }
        public string Fc { get; set; }
        public string SistolicaDerecha { get; set; }
        public string SistolicaIzquierda { get; set; }
        public string DiastolicaDerecha { get; set; }
        public string DiastolicaIzquierda { get; set; }
        public string PresionArterialMedia { get; set; }
        public string CervixUterino { get; set; }
        public string FUR { get; set; }
        public string FPP { get; set; }
        public string Pozo { get; set; }
        public string Visualiz { get; set; }
        public string Perc { get; set; }
        public int? Usuario { get; set; }
        public int? UsuarioUpdate { get; set; }
        public string FechaUpdate { get; set; }
        public int? Liquido { get; set; }
        public string UmbilicalIp { get; set; }
        public string UmbilicalPerc { get; set; }
        public string UmbilicalDiastole { get; set; }
        public string AcmIp { get; set; }
        public string AcmPerc { get; set; }
        public string AcmDiastole { get; set; }
        public string RpcIp { get; set; }
        public string RpcPerc { get; set; }
        public string RpcDiastole { get; set; }
        public string IstmoAorticoIp { get; set; }
        public string IstmoAorticoPerc { get; set; }
        public string IstmoAorticoDiastole { get; set; }
        public string DuctusVenosoIp { get; set; }
        public string DuctusVenosoPerc { get; set; }
        public string DuctusVenosoDiastole { get; set; }
        public string VenaUmbilicalIp { get; set; }
        public string VenaUmbilicalPerc { get; set; }
        public string VenaUmbilicalDiastole { get; set; }
        public int? Ritmo { get; set; }
        public int? Situs { get; set; }
        public int? PosicionEstomago { get; set; }
        public int? EjeCardio { get; set; }
        public int? TamañoCardio { get; set; }
        public int? Camaras { get; set; }
        public int? SalidaVentriIzquierdo { get; set; }
        public int? SalidaVentriDerecho { get; set; }
        public int? VasosTraquea { get; set; }
        public int? VistaEjeCortoVent { get; set; }
        public int? VistaEjeCortoAop { get; set; }
        public int? UnionAuriculoventricular { get; set; }
        public int? UnionVentriculoArterial { get; set; }
        public int? DerramePericardio { get; set; }
        public int? VenasSistematicas { get; set; }
        public int? VenasPulmonares { get; set; }
        public int? ForamenOval { get; set; }
        public int? ValvulasAtrioVento { get; set; }
        public int? TabiqueAuricular { get; set; }
        public int? TabiqueVentricular { get; set; }
        public int? ValvulasSemilunares { get; set; }
        public int? ArcoDuctal { get; set; }
        public int? ArcoAortico { get; set; }
        public string Biometria { get; set; }
        public string IndiceMiocardico { get; set; }
        public int? Anatomia { get; set; }
        public string AnatomiaTexto { get; set; }
    }
}
