namespace WebAppMaternidad.CapaEntidades
{
    public class EcoDopplerCrecimiento
    {
        public int? NumeroFeto { get; set; }
        public string Presentacion { get; set; }
        public string Dbp { get; set; }
        public string Cc { get; set; }
        public string Ca { get; set; }
        public string Lf { get; set; }
        public string Lh { get; set; }
        public string Peso { get; set; }
        public string Perc { get; set; }
        public int? Sexo { get; set; }
        public string Fc { get; set; }
        public int? Cordon { get; set; }
        public int? Placenta { get; set; }
        public int? Grado { get; set; }
        public string ILA { get; set; }
        public string Pozo { get; set; }
        public string Visualiz { get; set; }
        public int IdRealizaPrueba { get; set; }
        public int IdExamen { get; set; }
        public int IdProducto { get; set; }
        public int IdOrden { get; set; }
        public int? IdMedico { get; set; }
        public int IdMovimiento { get; set; }
        public int? Accion { get; set; }
        public string LiquidoAmn { get; set; }
        public string MovRespiratorios { get; set; }
        public string MovCorporales { get; set; }
        public string Tono { get; set; }
        public string Reactividad { get; set; }
        public string TotaL { get; set; }
        public string IpArtUmb { get; set; }
        public string AUmbilicalPerc { get; set; }
        public string AUmbilicalDiastole { get; set; }
        public string IpArtCMedia { get; set; }
        public string ACMPerc { get; set; }
        public string ACMDiastole { get; set; }
        public string IpRpc { get; set; }
        public string RPCPerc { get; set; }
        public string RPCDiastole { get; set; }
        public string VpsAcmIp { get; set; }
        public string VpsAcmPerc { get; set; }
        public string VpsAcmDiastole { get; set; }
        public string IpIsmoAortico { get; set; }
        public string IsmoAorticoPerc { get; set; }
        public string IsmoAorticoDiastole { get; set; }
        public string IpDucVen { get; set; }
        public string DuctoVenosoPerc { get; set; }
        public string DuctoVenosoDiastole { get; set; }
        public string IpUterinaDerecha { get; set; }
        public string IpUterinaIzquierda { get; set; }
        public string UterinasIpMedio { get; set; }
        public string UterinaPerc { get; set; }
        public string UterinaMom { get; set; }
        public string SistolicaDerecha { get; set; }
        public string SistolicaIzquierda { get; set; }
        public string DiastolicaDerecha { get; set; }
        public string DiastolicaIzquierda { get; set; }
        public string PresionArterialMedia { get; set; }
        public string CervixUterino { get; set; }
        public string FUR { get; set; }
        public string FPP { get; set; }
        public string EdadGestacional { get; set; }
        public string Observaciones { get; set; }
        public string Conclusion { get; set; }
        public string Sugerencia { get; set; }
        public int? Usuario { get; set; }
        public int? Anatomia { get; set; }
        public string AnatomiaTexto { get; set; }
        public int? Liquido { get; set; }
        public string VenaUmbIp { get; set; }
        public string VenaUmbPerc { get; set; }
        public string VenaUmbDiastole { get; set; }
        public string IpVpsAcm { get; set; }
        public string VpsACMPerc { get; set; }
        public string VpsACMDiastole { get; set; }
    }
}
