namespace WebAppMaternidad.CapaEntidades
{
    public class EcoMorfologica
    {
        public int Id { get; set; }
        public int? NumeroFeto { get; set; }
        public int? Presentacion { get; set; }
        public string Dbp { get; set; }
        public string Cc { get; set; }
        public string Ca { get; set; }
        public string Lf { get; set; }
        public string Lh { get; set; }
        public string Peso { get; set; }
        public string Sexo { get; set; }
        public string EdadGestacional { get; set; }
        public string PatronIntestinal { get; set; }
        public string GradoPlacentario { get; set; }
        public string CentroOsificacion { get; set; }
        public string Rel { get; set; }
        public string Total { get; set; }
        public string IpArtUmb { get; set; }
        public string IpDucVen { get; set; }
        public string IpArtCMedia { get; set; }
        public string VpsAcm { get; set; }
        public string IpIsmoAortico { get; set; }
        public int? Placenta { get; set; }
        public int? Grado { get; set; }
        public int? Cordon { get; set; }
        public string ILA { get; set; }
        public string IpUterinaDerecha { get; set; }
        public string IpUterinaIzquierda { get; set; }
        public string IpUterinaPromedio { get; set; }
        public string Observaciones { get; set; }
        public string Conclusion { get; set; }
        public string Sugerencia { get; set; }
        public string Fecha { get; set; }
        public int? IdProducto { get; set; }
        public int? IdOrden { get; set; }
        public int? IdRealizaPrueba { get; set; }
        public int? IdMovimiento { get; set; }
        public string Fc { get; set; }
        public int? Doppler { get; set; }
        public int? MorfFetal { get; set; }
        public string Cerebelo { get; set; }
        public string CisternaMagna { get; set; }
        public string VentriculoLateral { get; set; }
        public string DiametroInterocular { get; set; }
        public int? Corazon { get; set; }
        public int? Columna { get; set; }
        public int? CamaraGastrica { get; set; }
        public int? Snc { get; set; }
        public int? Cara { get; set; }
        public int? Cuello { get; set; }
        public int? Torax { get; set; }
        public int? GastroIntestinal { get; set; }
        public int? Urogenital { get; set; }
        public int? MusculoEsqueletico { get; set; }
        public int? Pies { get; set; }
        public int? Manos { get; set; }
        public int? ParedAbdominal { get; set; }
        public string UterinasIpMedio { get; set; }
        public string UterinaPerc { get; set; }
        public string UterinaMom { get; set; }
        public string MaternoDerecha { get; set; }
        public string MaternoIzquierda { get; set; }
        public string MaternoMedio { get; set; }
        public string MaternoPerc { get; set; }
        public string MaternoMom { get; set; }
        public string CervixUterino { get; set; }
        public string AUmbilicalPerc { get; set; }
        public string AUmbilicalDiastole { get; set; }
        public string ACMPerc { get; set; }
        public string ACMDiastole { get; set; }
        public string RPCPerc { get; set; }
        public string RPCDiastole { get; set; }
        public string IsmoAorticoPerc { get; set; }
        public string IsmoAorticoDiastole { get; set; }
        public string DuctoVenosoPerc { get; set; }
        public string DuctoVenosoDiastole { get; set; }
        public string PliegueNucal { get; set; }
        public string HuesoNasal { get; set; }
        public string AstaPosterior { get; set; }
        public string AstaAnterior { get; set; }
        public string FUR { get; set; }
        public string FPP { get; set; }
        public string Pozo { get; set; }
        public string Visualiz { get; set; }
        public string Perc { get; set; }
        public int? Usuario { get; set; }
        public int? UsuarioUpdate { get; set; }
        public string FechaUpdate { get; set; }
        public int? Liquido { get; set; }
        public string VenaUmbIp { get; set; }
        public string VenaUmbPerc { get; set; }
        public string VenaUmbDiastole { get; set; }
        public string SistolicaDerecha { get; set; }
        public string SistolicaIzquierda { get; set; }
        public string DiastolicaDerecha { get; set; }
        public string DiastolicaIzquierda { get; set; }
        public string PresionArterialMedia { get; set; }
        public int? Anatomia { get; set; }
        public string AnatomiaTexto { get; set; }
    }
}
