namespace WebAppMaternidad.CapaEntidades
{
    public class EcoNeurosonografia
    {
        //public int Id { get; set; }
        public int? NumeroFeto { get; set; }
        public int? Presentacion { get; set; }
        public string Dbp { get; set; }
        public string Cc { get; set; }
        public string Ca { get; set; }
        public string Lf { get; set; }
        public string Lh { get; set; }
        public string Peso { get; set; }
        public int? Sexo { get; set; }
        public string EdadGestacional { get; set; }
        public int? Placenta { get; set; }
        public int? Grado { get; set; }
        public int? Cordon { get; set; }
        public string ILA { get; set; }
        public string IpUterinaDerecha { get; set; }
        public string IpUterinaIzquierda { get; set; }
        public string UterinasIpMedio { get; set; }
        public string UterinaPerc { get; set; }
        public string UterinaMom { get; set; }
        public string Observaciones { get; set; }
        public string Conclusion { get; set; }
        public string Sugerencia { get; set; }
        public string Fecha { get; set; }
        public int? IdProducto { get; set; }
        public int? IdOrden { get; set; }
        public int? IdRealizaPrueba { get; set; }
        public int? IdMovimiento { get; set; }
        public string Fc { get; set; }
        public string SistolicaDerecha { get; set; }
        public string SistolicaIzquierda { get; set; }
        public string DiastolicaDerecha { get; set; }
        public string DiastolicaIzquierda { get; set; }
        public string PresionArterialMedia { get; set; }
        public string CervixUterino { get; set; }
        public string FUR { get; set; }
        public string FPP { get; set; }
        public string Pozo { get; set; }
        public string Visualiz { get; set; }
        public string Perc { get; set; }
        public int? Usuario { get; set; }
        public int? UsuarioUpdate { get; set; }
        public string FechaUpdate { get; set; }
        public int? Liquido { get; set; }
        public string UmbilicalIp { get; set; }
        public string UmbilicalPerc { get; set; }
        public string UmbilicalDiastole { get; set; }
        public string AcmIp { get; set; }
        public string AcmPerc { get; set; }
        public string AcmDiastole { get; set; }
        public string RpcIp { get; set; }
        public string RpcPerc { get; set; }
        public string RpcDiastole { get; set; }
        public string IstmoAorticoIp { get; set; }
        public string IstmoAorticoPerc { get; set; }
        public string IstmoAorticoDiastole { get; set; }
        public string DuctusVenosoIp { get; set; }
        public string DuctusVenosoPerc { get; set; }
        public string DuctusVenosoDiastole { get; set; }
        public string VenaUmbilicalIp { get; set; }
        public string VenaUmbilicalPerc { get; set; }
        public string VenaUmbilicalDiastole { get; set; }
        public int? Craneo { get; set; }
        public int? CisuraInterhem { get; set; }
        public int? Cavum { get; set; }
        public string AstaPosterior { get; set; }
        public string AstaInferior { get; set; }
        public int? TercerVentriculo { get; set; }
        public int? EspSubracnoid { get; set; }
        public int? Hemisferios { get; set; }
        public int? Cisuras { get; set; }
        public string DiametroCerebro { get; set; }
        public int? Cerebelo { get; set; }
        public string CisternaMagna { get; set; }
        public int? Vermis { get; set; }
        public int? Tentorio { get; set; }
        public int? CuerpoCalloso { get; set; }
        public int? Columna { get; set; }
        public int? Anatomia { get; set; }
        public string AnatomiaTexto { get; set; }
    }
}
