//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SisReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sis.gob.pe/", ConfigurationName="SisReference.RecepcionTramaSoap")]
    public interface RecepcionTramaSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Disa del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAsegurados", ReplyAction="*")]
        SisReference.BuscarAseguradosResponse BuscarAsegurados(SisReference.BuscarAseguradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAsegurados", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.BuscarAseguradosResponse> BuscarAseguradosAsync(SisReference.BuscarAseguradosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosPE", ReplyAction="*")]
        SisReference.BuscarAseguradosPEResponse BuscarAseguradosPE(SisReference.BuscarAseguradosPERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosPE", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.BuscarAseguradosPEResponse> BuscarAseguradosPEAsync(SisReference.BuscarAseguradosPERequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosARFSISV2", ReplyAction="*")]
        SisReference.BuscarAseguradosARFSISV2Response BuscarAseguradosARFSISV2(SisReference.BuscarAseguradosARFSISV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarAseguradosARFSISV2", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.BuscarAseguradosARFSISV2Response> BuscarAseguradosARFSISV2Async(SisReference.BuscarAseguradosARFSISV2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC40V2", ReplyAction="*")]
        SisReference.Validar_RC40V2Response Validar_RC40V2(SisReference.Validar_RC40V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC40V2", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.Validar_RC40V2Response> Validar_RC40V2Async(SisReference.Validar_RC40V2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC41V2", ReplyAction="*")]
        SisReference.Validar_RC41V2Response Validar_RC41V2(SisReference.Validar_RC41V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC41V2", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.Validar_RC41V2Response> Validar_RC41V2Async(SisReference.Validar_RC41V2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC42V3", ReplyAction="*")]
        SisReference.Validar_RC42V3Response Validar_RC42V3(SisReference.Validar_RC42V3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC42V3", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.Validar_RC42V3Response> Validar_RC42V3Async(SisReference.Validar_RC42V3Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC42V2", ReplyAction="*")]
        SisReference.Validar_RC42V2Response Validar_RC42V2(SisReference.Validar_RC42V2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Validar_RC42V2", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.Validar_RC42V2Response> Validar_RC42V2Async(SisReference.Validar_RC42V2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Consulta_Retroarfsis", ReplyAction="*")]
        SisReference.Consulta_RetroarfsisResponse Consulta_Retroarfsis(SisReference.Consulta_RetroarfsisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/Consulta_Retroarfsis", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.Consulta_RetroarfsisResponse> Consulta_RetroarfsisAsync(SisReference.Consulta_RetroarfsisRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/VerificaFUADuplicadoV2", ReplyAction="*")]
        SisReference.VerificaFUADuplicadoV2Response VerificaFUADuplicadoV2(SisReference.VerificaFUADuplicadoV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/VerificaFUADuplicadoV2", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.VerificaFUADuplicadoV2Response> VerificaFUADuplicadoV2Async(SisReference.VerificaFUADuplicadoV2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarPersonalSaludV3", ReplyAction="*")]
        SisReference.BuscarPersonalSaludV3Response BuscarPersonalSaludV3(SisReference.BuscarPersonalSaludV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarPersonalSaludV3", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.BuscarPersonalSaludV3Response> BuscarPersonalSaludV3Async(SisReference.BuscarPersonalSaludV3Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://www.sis.gob.pe/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarPersonalSaludV2", ReplyAction="*")]
        SisReference.BuscarPersonalSaludV2Response BuscarPersonalSaludV2(SisReference.BuscarPersonalSaludV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sis.gob.pe/BuscarPersonalSaludV2", ReplyAction="*")]
        System.Threading.Tasks.Task<SisReference.BuscarPersonalSaludV2Response> BuscarPersonalSaludV2Async(SisReference.BuscarPersonalSaludV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAseguradosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAsegurados", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarAseguradosRequestBody Body;
        
        public BuscarAseguradosRequest()
        {
        }
        
        public BuscarAseguradosRequest(SisReference.BuscarAseguradosRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarAseguradosRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Disa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TipoFormato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Correlativo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CodTabla;
        
        public BuscarAseguradosRequestBody()
        {
        }
        
        public BuscarAseguradosRequestBody(string Disa, string TipoFormato, string Contrato, string Correlativo, string CodTabla)
        {
            this.Disa = Disa;
            this.TipoFormato = TipoFormato;
            this.Contrato = Contrato;
            this.Correlativo = Correlativo;
            this.CodTabla = CodTabla;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAseguradosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAseguradosResponse", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarAseguradosResponseBody Body;
        
        public BuscarAseguradosResponse()
        {
        }
        
        public BuscarAseguradosResponse(SisReference.BuscarAseguradosResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarAseguradosResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarAseguradosResult;
        
        public BuscarAseguradosResponseBody()
        {
        }
        
        public BuscarAseguradosResponseBody(string BuscarAseguradosResult)
        {
            this.BuscarAseguradosResult = BuscarAseguradosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAseguradosPERequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAseguradosPE", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarAseguradosPERequestBody Body;
        
        public BuscarAseguradosPERequest()
        {
        }
        
        public BuscarAseguradosPERequest(SisReference.BuscarAseguradosPERequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarAseguradosPERequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sDNIResponsable;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sOpcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sTipoDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string sDoc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string sDisa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string sTipoFormato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string sContrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string sCorrelativo;
        
        public BuscarAseguradosPERequestBody()
        {
        }
        
        public BuscarAseguradosPERequestBody(string sUsuario, string sPassword, string sDNIResponsable, string sOpcion, string sTipoDoc, string sDoc, string sDisa, string sTipoFormato, string sContrato, string sCorrelativo)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.sDNIResponsable = sDNIResponsable;
            this.sOpcion = sOpcion;
            this.sTipoDoc = sTipoDoc;
            this.sDoc = sDoc;
            this.sDisa = sDisa;
            this.sTipoFormato = sTipoFormato;
            this.sContrato = sContrato;
            this.sCorrelativo = sCorrelativo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAseguradosPEResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAseguradosPEResponse", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarAseguradosPEResponseBody Body;
        
        public BuscarAseguradosPEResponse()
        {
        }
        
        public BuscarAseguradosPEResponse(SisReference.BuscarAseguradosPEResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarAseguradosPEResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarAseguradosPEResult;
        
        public BuscarAseguradosPEResponseBody()
        {
        }
        
        public BuscarAseguradosPEResponseBody(string BuscarAseguradosPEResult)
        {
            this.BuscarAseguradosPEResult = BuscarAseguradosPEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAseguradosARFSISV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAseguradosARFSISV2", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarAseguradosARFSISV2RequestBody Body;
        
        public BuscarAseguradosARFSISV2Request()
        {
        }
        
        public BuscarAseguradosARFSISV2Request(SisReference.BuscarAseguradosARFSISV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarAseguradosARFSISV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Disa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoFormato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Contrato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Correlativo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CodTabla;
        
        public BuscarAseguradosARFSISV2RequestBody()
        {
        }
        
        public BuscarAseguradosARFSISV2RequestBody(string sUsuario, string sPassword, string Disa, string TipoFormato, string Contrato, string Correlativo, string CodTabla)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.Disa = Disa;
            this.TipoFormato = TipoFormato;
            this.Contrato = Contrato;
            this.Correlativo = Correlativo;
            this.CodTabla = CodTabla;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarAseguradosARFSISV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarAseguradosARFSISV2Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarAseguradosARFSISV2ResponseBody Body;
        
        public BuscarAseguradosARFSISV2Response()
        {
        }
        
        public BuscarAseguradosARFSISV2Response(SisReference.BuscarAseguradosARFSISV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarAseguradosARFSISV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarAseguradosARFSISV2Result;
        
        public BuscarAseguradosARFSISV2ResponseBody()
        {
        }
        
        public BuscarAseguradosARFSISV2ResponseBody(string BuscarAseguradosARFSISV2Result)
        {
            this.BuscarAseguradosARFSISV2Result = BuscarAseguradosARFSISV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC40V2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC40V2", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC40V2RequestBody Body;
        
        public Validar_RC40V2Request()
        {
        }
        
        public Validar_RC40V2Request(SisReference.Validar_RC40V2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC40V2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string disaFua;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string lotefua;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string numerofua;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string destinoFua;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string modalidad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime fecate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime fecing;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime feccorte;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string disavin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string lotevin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string numevin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string udrautorizavin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string loteautorizavin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string secautorizavin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string disaafi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string loteafi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string numafi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string secafi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string tablaafi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string compoafi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string V_FLAG_VALIDACION;
        
        public Validar_RC40V2RequestBody()
        {
        }
        
        public Validar_RC40V2RequestBody(
                    string sUsuario, 
                    string sPassword, 
                    string disaFua, 
                    string lotefua, 
                    string numerofua, 
                    string destinoFua, 
                    string modalidad, 
                    System.DateTime fecate, 
                    System.DateTime fecing, 
                    System.DateTime feccorte, 
                    string disavin, 
                    string lotevin, 
                    string numevin, 
                    string udrautorizavin, 
                    string loteautorizavin, 
                    string secautorizavin, 
                    string disaafi, 
                    string loteafi, 
                    string numafi, 
                    string secafi, 
                    string tablaafi, 
                    string compoafi, 
                    string V_FLAG_VALIDACION)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.disaFua = disaFua;
            this.lotefua = lotefua;
            this.numerofua = numerofua;
            this.destinoFua = destinoFua;
            this.modalidad = modalidad;
            this.fecate = fecate;
            this.fecing = fecing;
            this.feccorte = feccorte;
            this.disavin = disavin;
            this.lotevin = lotevin;
            this.numevin = numevin;
            this.udrautorizavin = udrautorizavin;
            this.loteautorizavin = loteautorizavin;
            this.secautorizavin = secautorizavin;
            this.disaafi = disaafi;
            this.loteafi = loteafi;
            this.numafi = numafi;
            this.secafi = secafi;
            this.tablaafi = tablaafi;
            this.compoafi = compoafi;
            this.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC40V2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC40V2Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC40V2ResponseBody Body;
        
        public Validar_RC40V2Response()
        {
        }
        
        public Validar_RC40V2Response(SisReference.Validar_RC40V2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC40V2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Validar_RC40V2Result;
        
        public Validar_RC40V2ResponseBody()
        {
        }
        
        public Validar_RC40V2ResponseBody(string Validar_RC40V2Result)
        {
            this.Validar_RC40V2Result = Validar_RC40V2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC41V2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC41V2", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC41V2RequestBody Body;
        
        public Validar_RC41V2Request()
        {
        }
        
        public Validar_RC41V2Request(SisReference.Validar_RC41V2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC41V2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numeroSolicitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string afiDisa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string afiLote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string afiNumero;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string afiSecuencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string afiTabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string afiComponente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string afiStuacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public double montoTotalConsignado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string V_FLAG_VALIDACION;
        
        public Validar_RC41V2RequestBody()
        {
        }
        
        public Validar_RC41V2RequestBody(string sUsuario, string sPassword, string numeroSolicitud, string afiDisa, string afiLote, string afiNumero, string afiSecuencia, string afiTabla, string afiComponente, string afiStuacion, double montoTotalConsignado, string V_FLAG_VALIDACION)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.numeroSolicitud = numeroSolicitud;
            this.afiDisa = afiDisa;
            this.afiLote = afiLote;
            this.afiNumero = afiNumero;
            this.afiSecuencia = afiSecuencia;
            this.afiTabla = afiTabla;
            this.afiComponente = afiComponente;
            this.afiStuacion = afiStuacion;
            this.montoTotalConsignado = montoTotalConsignado;
            this.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC41V2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC41V2Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC41V2ResponseBody Body;
        
        public Validar_RC41V2Response()
        {
        }
        
        public Validar_RC41V2Response(SisReference.Validar_RC41V2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC41V2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Validar_RC41V2Result;
        
        public Validar_RC41V2ResponseBody()
        {
        }
        
        public Validar_RC41V2ResponseBody(string Validar_RC41V2Result)
        {
            this.Validar_RC41V2Result = Validar_RC41V2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC42V3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC42V3", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC42V3RequestBody Body;
        
        public Validar_RC42V3Request()
        {
        }
        
        public Validar_RC42V3Request(SisReference.Validar_RC42V3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC42V3RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string servicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string disa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string lote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string numformato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string secuencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string tabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string componente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string destino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string V_FLAG_VALIDACION;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string idafi;
        
        public Validar_RC42V3RequestBody()
        {
        }
        
        public Validar_RC42V3RequestBody(string sUsuario, string sPassword, string servicio, System.DateTime fecate, string disa, string lote, string numformato, string secuencia, string tabla, string componente, string destino, string V_FLAG_VALIDACION, string idafi)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.servicio = servicio;
            this.fecate = fecate;
            this.disa = disa;
            this.lote = lote;
            this.numformato = numformato;
            this.secuencia = secuencia;
            this.tabla = tabla;
            this.componente = componente;
            this.destino = destino;
            this.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            this.idafi = idafi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC42V3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC42V3Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC42V3ResponseBody Body;
        
        public Validar_RC42V3Response()
        {
        }
        
        public Validar_RC42V3Response(SisReference.Validar_RC42V3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC42V3ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Validar_RC42V3Result;
        
        public Validar_RC42V3ResponseBody()
        {
        }
        
        public Validar_RC42V3ResponseBody(string Validar_RC42V3Result)
        {
            this.Validar_RC42V3Result = Validar_RC42V3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC42V2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC42V2", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC42V2RequestBody Body;
        
        public Validar_RC42V2Request()
        {
        }
        
        public Validar_RC42V2Request(SisReference.Validar_RC42V2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC42V2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string servicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string disa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string lote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string numformato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string secuencia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string tabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string componente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string destino;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string V_FLAG_VALIDACION;
        
        public Validar_RC42V2RequestBody()
        {
        }
        
        public Validar_RC42V2RequestBody(string sUsuario, string sPassword, string servicio, System.DateTime fecate, string disa, string lote, string numformato, string secuencia, string tabla, string componente, string destino, string V_FLAG_VALIDACION)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.servicio = servicio;
            this.fecate = fecate;
            this.disa = disa;
            this.lote = lote;
            this.numformato = numformato;
            this.secuencia = secuencia;
            this.tabla = tabla;
            this.componente = componente;
            this.destino = destino;
            this.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Validar_RC42V2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validar_RC42V2Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Validar_RC42V2ResponseBody Body;
        
        public Validar_RC42V2Response()
        {
        }
        
        public Validar_RC42V2Response(SisReference.Validar_RC42V2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Validar_RC42V2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Validar_RC42V2Result;
        
        public Validar_RC42V2ResponseBody()
        {
        }
        
        public Validar_RC42V2ResponseBody(string Validar_RC42V2Result)
        {
            this.Validar_RC42V2Result = Validar_RC42V2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_RetroarfsisRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_Retroarfsis", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Consulta_RetroarfsisRequestBody Body;
        
        public Consulta_RetroarfsisRequest()
        {
        }
        
        public Consulta_RetroarfsisRequest(SisReference.Consulta_RetroarfsisRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Consulta_RetroarfsisRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string opcion;
        
        public Consulta_RetroarfsisRequestBody()
        {
        }
        
        public Consulta_RetroarfsisRequestBody(string sUsuario, string sPassword, string opcion)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.opcion = opcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consulta_RetroarfsisResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consulta_RetroarfsisResponse", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.Consulta_RetroarfsisResponseBody Body;
        
        public Consulta_RetroarfsisResponse()
        {
        }
        
        public Consulta_RetroarfsisResponse(SisReference.Consulta_RetroarfsisResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class Consulta_RetroarfsisResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Consulta_RetroarfsisResult;
        
        public Consulta_RetroarfsisResponseBody()
        {
        }
        
        public Consulta_RetroarfsisResponseBody(string Consulta_RetroarfsisResult)
        {
            this.Consulta_RetroarfsisResult = Consulta_RetroarfsisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaFUADuplicadoV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaFUADuplicadoV2", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.VerificaFUADuplicadoV2RequestBody Body;
        
        public VerificaFUADuplicadoV2Request()
        {
        }
        
        public VerificaFUADuplicadoV2Request(SisReference.VerificaFUADuplicadoV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class VerificaFUADuplicadoV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Disa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TipoFormato;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Numero;
        
        public VerificaFUADuplicadoV2RequestBody()
        {
        }
        
        public VerificaFUADuplicadoV2RequestBody(string sUsuario, string sPassword, string Disa, string TipoFormato, string Numero)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.Disa = Disa;
            this.TipoFormato = TipoFormato;
            this.Numero = Numero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaFUADuplicadoV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaFUADuplicadoV2Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.VerificaFUADuplicadoV2ResponseBody Body;
        
        public VerificaFUADuplicadoV2Response()
        {
        }
        
        public VerificaFUADuplicadoV2Response(SisReference.VerificaFUADuplicadoV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class VerificaFUADuplicadoV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VerificaFUADuplicadoV2Result;
        
        public VerificaFUADuplicadoV2ResponseBody()
        {
        }
        
        public VerificaFUADuplicadoV2ResponseBody(string VerificaFUADuplicadoV2Result)
        {
            this.VerificaFUADuplicadoV2Result = VerificaFUADuplicadoV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonalSaludV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonalSaludV3", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarPersonalSaludV3RequestBody Body;
        
        public BuscarPersonalSaludV3Request()
        {
        }
        
        public BuscarPersonalSaludV3Request(SisReference.BuscarPersonalSaludV3RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarPersonalSaludV3RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TipoDocumento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Documento;
        
        public BuscarPersonalSaludV3RequestBody()
        {
        }
        
        public BuscarPersonalSaludV3RequestBody(string sUsuario, string sPassword, string TipoDocumento, string Documento)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.TipoDocumento = TipoDocumento;
            this.Documento = Documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonalSaludV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonalSaludV3Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarPersonalSaludV3ResponseBody Body;
        
        public BuscarPersonalSaludV3Response()
        {
        }
        
        public BuscarPersonalSaludV3Response(SisReference.BuscarPersonalSaludV3ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarPersonalSaludV3ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarPersonalSaludV3Result;
        
        public BuscarPersonalSaludV3ResponseBody()
        {
        }
        
        public BuscarPersonalSaludV3ResponseBody(string BuscarPersonalSaludV3Result)
        {
            this.BuscarPersonalSaludV3Result = BuscarPersonalSaludV3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonalSaludV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonalSaludV2", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarPersonalSaludV2RequestBody Body;
        
        public BuscarPersonalSaludV2Request()
        {
        }
        
        public BuscarPersonalSaludV2Request(SisReference.BuscarPersonalSaludV2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarPersonalSaludV2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Documento;
        
        public BuscarPersonalSaludV2RequestBody()
        {
        }
        
        public BuscarPersonalSaludV2RequestBody(string sUsuario, string sPassword, string Documento)
        {
            this.sUsuario = sUsuario;
            this.sPassword = sPassword;
            this.Documento = Documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarPersonalSaludV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarPersonalSaludV2Response", Namespace="http://www.sis.gob.pe/", Order=0)]
        public SisReference.BuscarPersonalSaludV2ResponseBody Body;
        
        public BuscarPersonalSaludV2Response()
        {
        }
        
        public BuscarPersonalSaludV2Response(SisReference.BuscarPersonalSaludV2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sis.gob.pe/")]
    public partial class BuscarPersonalSaludV2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BuscarPersonalSaludV2Result;
        
        public BuscarPersonalSaludV2ResponseBody()
        {
        }
        
        public BuscarPersonalSaludV2ResponseBody(string BuscarPersonalSaludV2Result)
        {
            this.BuscarPersonalSaludV2Result = BuscarPersonalSaludV2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface RecepcionTramaSoapChannel : SisReference.RecepcionTramaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class RecepcionTramaSoapClient : System.ServiceModel.ClientBase<SisReference.RecepcionTramaSoap>, SisReference.RecepcionTramaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RecepcionTramaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(RecepcionTramaSoapClient.GetBindingForEndpoint(endpointConfiguration), RecepcionTramaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcionTramaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecepcionTramaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcionTramaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecepcionTramaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RecepcionTramaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.BuscarAseguradosResponse SisReference.RecepcionTramaSoap.BuscarAsegurados(SisReference.BuscarAseguradosRequest request)
        {
            return base.Channel.BuscarAsegurados(request);
        }
        
        public string BuscarAsegurados(string Disa, string TipoFormato, string Contrato, string Correlativo, string CodTabla)
        {
            SisReference.BuscarAseguradosRequest inValue = new SisReference.BuscarAseguradosRequest();
            inValue.Body = new SisReference.BuscarAseguradosRequestBody();
            inValue.Body.Disa = Disa;
            inValue.Body.TipoFormato = TipoFormato;
            inValue.Body.Contrato = Contrato;
            inValue.Body.Correlativo = Correlativo;
            inValue.Body.CodTabla = CodTabla;
            SisReference.BuscarAseguradosResponse retVal = ((SisReference.RecepcionTramaSoap)(this)).BuscarAsegurados(inValue);
            return retVal.Body.BuscarAseguradosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.BuscarAseguradosResponse> SisReference.RecepcionTramaSoap.BuscarAseguradosAsync(SisReference.BuscarAseguradosRequest request)
        {
            return base.Channel.BuscarAseguradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.BuscarAseguradosResponse> BuscarAseguradosAsync(string Disa, string TipoFormato, string Contrato, string Correlativo, string CodTabla)
        {
            SisReference.BuscarAseguradosRequest inValue = new SisReference.BuscarAseguradosRequest();
            inValue.Body = new SisReference.BuscarAseguradosRequestBody();
            inValue.Body.Disa = Disa;
            inValue.Body.TipoFormato = TipoFormato;
            inValue.Body.Contrato = Contrato;
            inValue.Body.Correlativo = Correlativo;
            inValue.Body.CodTabla = CodTabla;
            return ((SisReference.RecepcionTramaSoap)(this)).BuscarAseguradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.BuscarAseguradosPEResponse SisReference.RecepcionTramaSoap.BuscarAseguradosPE(SisReference.BuscarAseguradosPERequest request)
        {
            return base.Channel.BuscarAseguradosPE(request);
        }
        
        public string BuscarAseguradosPE(string sUsuario, string sPassword, string sDNIResponsable, string sOpcion, string sTipoDoc, string sDoc, string sDisa, string sTipoFormato, string sContrato, string sCorrelativo)
        {
            SisReference.BuscarAseguradosPERequest inValue = new SisReference.BuscarAseguradosPERequest();
            inValue.Body = new SisReference.BuscarAseguradosPERequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sDNIResponsable = sDNIResponsable;
            inValue.Body.sOpcion = sOpcion;
            inValue.Body.sTipoDoc = sTipoDoc;
            inValue.Body.sDoc = sDoc;
            inValue.Body.sDisa = sDisa;
            inValue.Body.sTipoFormato = sTipoFormato;
            inValue.Body.sContrato = sContrato;
            inValue.Body.sCorrelativo = sCorrelativo;
            SisReference.BuscarAseguradosPEResponse retVal = ((SisReference.RecepcionTramaSoap)(this)).BuscarAseguradosPE(inValue);
            return retVal.Body.BuscarAseguradosPEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.BuscarAseguradosPEResponse> SisReference.RecepcionTramaSoap.BuscarAseguradosPEAsync(SisReference.BuscarAseguradosPERequest request)
        {
            return base.Channel.BuscarAseguradosPEAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.BuscarAseguradosPEResponse> BuscarAseguradosPEAsync(string sUsuario, string sPassword, string sDNIResponsable, string sOpcion, string sTipoDoc, string sDoc, string sDisa, string sTipoFormato, string sContrato, string sCorrelativo)
        {
            SisReference.BuscarAseguradosPERequest inValue = new SisReference.BuscarAseguradosPERequest();
            inValue.Body = new SisReference.BuscarAseguradosPERequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.sDNIResponsable = sDNIResponsable;
            inValue.Body.sOpcion = sOpcion;
            inValue.Body.sTipoDoc = sTipoDoc;
            inValue.Body.sDoc = sDoc;
            inValue.Body.sDisa = sDisa;
            inValue.Body.sTipoFormato = sTipoFormato;
            inValue.Body.sContrato = sContrato;
            inValue.Body.sCorrelativo = sCorrelativo;
            return ((SisReference.RecepcionTramaSoap)(this)).BuscarAseguradosPEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.BuscarAseguradosARFSISV2Response SisReference.RecepcionTramaSoap.BuscarAseguradosARFSISV2(SisReference.BuscarAseguradosARFSISV2Request request)
        {
            return base.Channel.BuscarAseguradosARFSISV2(request);
        }
        
        public string BuscarAseguradosARFSISV2(string sUsuario, string sPassword, string Disa, string TipoFormato, string Contrato, string Correlativo, string CodTabla)
        {
            SisReference.BuscarAseguradosARFSISV2Request inValue = new SisReference.BuscarAseguradosARFSISV2Request();
            inValue.Body = new SisReference.BuscarAseguradosARFSISV2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.Disa = Disa;
            inValue.Body.TipoFormato = TipoFormato;
            inValue.Body.Contrato = Contrato;
            inValue.Body.Correlativo = Correlativo;
            inValue.Body.CodTabla = CodTabla;
            SisReference.BuscarAseguradosARFSISV2Response retVal = ((SisReference.RecepcionTramaSoap)(this)).BuscarAseguradosARFSISV2(inValue);
            return retVal.Body.BuscarAseguradosARFSISV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.BuscarAseguradosARFSISV2Response> SisReference.RecepcionTramaSoap.BuscarAseguradosARFSISV2Async(SisReference.BuscarAseguradosARFSISV2Request request)
        {
            return base.Channel.BuscarAseguradosARFSISV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.BuscarAseguradosARFSISV2Response> BuscarAseguradosARFSISV2Async(string sUsuario, string sPassword, string Disa, string TipoFormato, string Contrato, string Correlativo, string CodTabla)
        {
            SisReference.BuscarAseguradosARFSISV2Request inValue = new SisReference.BuscarAseguradosARFSISV2Request();
            inValue.Body = new SisReference.BuscarAseguradosARFSISV2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.Disa = Disa;
            inValue.Body.TipoFormato = TipoFormato;
            inValue.Body.Contrato = Contrato;
            inValue.Body.Correlativo = Correlativo;
            inValue.Body.CodTabla = CodTabla;
            return ((SisReference.RecepcionTramaSoap)(this)).BuscarAseguradosARFSISV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.Validar_RC40V2Response SisReference.RecepcionTramaSoap.Validar_RC40V2(SisReference.Validar_RC40V2Request request)
        {
            return base.Channel.Validar_RC40V2(request);
        }
        
        public string Validar_RC40V2(
                    string sUsuario, 
                    string sPassword, 
                    string disaFua, 
                    string lotefua, 
                    string numerofua, 
                    string destinoFua, 
                    string modalidad, 
                    System.DateTime fecate, 
                    System.DateTime fecing, 
                    System.DateTime feccorte, 
                    string disavin, 
                    string lotevin, 
                    string numevin, 
                    string udrautorizavin, 
                    string loteautorizavin, 
                    string secautorizavin, 
                    string disaafi, 
                    string loteafi, 
                    string numafi, 
                    string secafi, 
                    string tablaafi, 
                    string compoafi, 
                    string V_FLAG_VALIDACION)
        {
            SisReference.Validar_RC40V2Request inValue = new SisReference.Validar_RC40V2Request();
            inValue.Body = new SisReference.Validar_RC40V2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.disaFua = disaFua;
            inValue.Body.lotefua = lotefua;
            inValue.Body.numerofua = numerofua;
            inValue.Body.destinoFua = destinoFua;
            inValue.Body.modalidad = modalidad;
            inValue.Body.fecate = fecate;
            inValue.Body.fecing = fecing;
            inValue.Body.feccorte = feccorte;
            inValue.Body.disavin = disavin;
            inValue.Body.lotevin = lotevin;
            inValue.Body.numevin = numevin;
            inValue.Body.udrautorizavin = udrautorizavin;
            inValue.Body.loteautorizavin = loteautorizavin;
            inValue.Body.secautorizavin = secautorizavin;
            inValue.Body.disaafi = disaafi;
            inValue.Body.loteafi = loteafi;
            inValue.Body.numafi = numafi;
            inValue.Body.secafi = secafi;
            inValue.Body.tablaafi = tablaafi;
            inValue.Body.compoafi = compoafi;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            SisReference.Validar_RC40V2Response retVal = ((SisReference.RecepcionTramaSoap)(this)).Validar_RC40V2(inValue);
            return retVal.Body.Validar_RC40V2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.Validar_RC40V2Response> SisReference.RecepcionTramaSoap.Validar_RC40V2Async(SisReference.Validar_RC40V2Request request)
        {
            return base.Channel.Validar_RC40V2Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.Validar_RC40V2Response> Validar_RC40V2Async(
                    string sUsuario, 
                    string sPassword, 
                    string disaFua, 
                    string lotefua, 
                    string numerofua, 
                    string destinoFua, 
                    string modalidad, 
                    System.DateTime fecate, 
                    System.DateTime fecing, 
                    System.DateTime feccorte, 
                    string disavin, 
                    string lotevin, 
                    string numevin, 
                    string udrautorizavin, 
                    string loteautorizavin, 
                    string secautorizavin, 
                    string disaafi, 
                    string loteafi, 
                    string numafi, 
                    string secafi, 
                    string tablaafi, 
                    string compoafi, 
                    string V_FLAG_VALIDACION)
        {
            SisReference.Validar_RC40V2Request inValue = new SisReference.Validar_RC40V2Request();
            inValue.Body = new SisReference.Validar_RC40V2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.disaFua = disaFua;
            inValue.Body.lotefua = lotefua;
            inValue.Body.numerofua = numerofua;
            inValue.Body.destinoFua = destinoFua;
            inValue.Body.modalidad = modalidad;
            inValue.Body.fecate = fecate;
            inValue.Body.fecing = fecing;
            inValue.Body.feccorte = feccorte;
            inValue.Body.disavin = disavin;
            inValue.Body.lotevin = lotevin;
            inValue.Body.numevin = numevin;
            inValue.Body.udrautorizavin = udrautorizavin;
            inValue.Body.loteautorizavin = loteautorizavin;
            inValue.Body.secautorizavin = secautorizavin;
            inValue.Body.disaafi = disaafi;
            inValue.Body.loteafi = loteafi;
            inValue.Body.numafi = numafi;
            inValue.Body.secafi = secafi;
            inValue.Body.tablaafi = tablaafi;
            inValue.Body.compoafi = compoafi;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            return ((SisReference.RecepcionTramaSoap)(this)).Validar_RC40V2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.Validar_RC41V2Response SisReference.RecepcionTramaSoap.Validar_RC41V2(SisReference.Validar_RC41V2Request request)
        {
            return base.Channel.Validar_RC41V2(request);
        }
        
        public string Validar_RC41V2(string sUsuario, string sPassword, string numeroSolicitud, string afiDisa, string afiLote, string afiNumero, string afiSecuencia, string afiTabla, string afiComponente, string afiStuacion, double montoTotalConsignado, string V_FLAG_VALIDACION)
        {
            SisReference.Validar_RC41V2Request inValue = new SisReference.Validar_RC41V2Request();
            inValue.Body = new SisReference.Validar_RC41V2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.numeroSolicitud = numeroSolicitud;
            inValue.Body.afiDisa = afiDisa;
            inValue.Body.afiLote = afiLote;
            inValue.Body.afiNumero = afiNumero;
            inValue.Body.afiSecuencia = afiSecuencia;
            inValue.Body.afiTabla = afiTabla;
            inValue.Body.afiComponente = afiComponente;
            inValue.Body.afiStuacion = afiStuacion;
            inValue.Body.montoTotalConsignado = montoTotalConsignado;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            SisReference.Validar_RC41V2Response retVal = ((SisReference.RecepcionTramaSoap)(this)).Validar_RC41V2(inValue);
            return retVal.Body.Validar_RC41V2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.Validar_RC41V2Response> SisReference.RecepcionTramaSoap.Validar_RC41V2Async(SisReference.Validar_RC41V2Request request)
        {
            return base.Channel.Validar_RC41V2Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.Validar_RC41V2Response> Validar_RC41V2Async(string sUsuario, string sPassword, string numeroSolicitud, string afiDisa, string afiLote, string afiNumero, string afiSecuencia, string afiTabla, string afiComponente, string afiStuacion, double montoTotalConsignado, string V_FLAG_VALIDACION)
        {
            SisReference.Validar_RC41V2Request inValue = new SisReference.Validar_RC41V2Request();
            inValue.Body = new SisReference.Validar_RC41V2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.numeroSolicitud = numeroSolicitud;
            inValue.Body.afiDisa = afiDisa;
            inValue.Body.afiLote = afiLote;
            inValue.Body.afiNumero = afiNumero;
            inValue.Body.afiSecuencia = afiSecuencia;
            inValue.Body.afiTabla = afiTabla;
            inValue.Body.afiComponente = afiComponente;
            inValue.Body.afiStuacion = afiStuacion;
            inValue.Body.montoTotalConsignado = montoTotalConsignado;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            return ((SisReference.RecepcionTramaSoap)(this)).Validar_RC41V2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.Validar_RC42V3Response SisReference.RecepcionTramaSoap.Validar_RC42V3(SisReference.Validar_RC42V3Request request)
        {
            return base.Channel.Validar_RC42V3(request);
        }
        
        public string Validar_RC42V3(string sUsuario, string sPassword, string servicio, System.DateTime fecate, string disa, string lote, string numformato, string secuencia, string tabla, string componente, string destino, string V_FLAG_VALIDACION, string idafi)
        {
            SisReference.Validar_RC42V3Request inValue = new SisReference.Validar_RC42V3Request();
            inValue.Body = new SisReference.Validar_RC42V3RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.servicio = servicio;
            inValue.Body.fecate = fecate;
            inValue.Body.disa = disa;
            inValue.Body.lote = lote;
            inValue.Body.numformato = numformato;
            inValue.Body.secuencia = secuencia;
            inValue.Body.tabla = tabla;
            inValue.Body.componente = componente;
            inValue.Body.destino = destino;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            inValue.Body.idafi = idafi;
            SisReference.Validar_RC42V3Response retVal = ((SisReference.RecepcionTramaSoap)(this)).Validar_RC42V3(inValue);
            return retVal.Body.Validar_RC42V3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.Validar_RC42V3Response> SisReference.RecepcionTramaSoap.Validar_RC42V3Async(SisReference.Validar_RC42V3Request request)
        {
            return base.Channel.Validar_RC42V3Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.Validar_RC42V3Response> Validar_RC42V3Async(string sUsuario, string sPassword, string servicio, System.DateTime fecate, string disa, string lote, string numformato, string secuencia, string tabla, string componente, string destino, string V_FLAG_VALIDACION, string idafi)
        {
            SisReference.Validar_RC42V3Request inValue = new SisReference.Validar_RC42V3Request();
            inValue.Body = new SisReference.Validar_RC42V3RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.servicio = servicio;
            inValue.Body.fecate = fecate;
            inValue.Body.disa = disa;
            inValue.Body.lote = lote;
            inValue.Body.numformato = numformato;
            inValue.Body.secuencia = secuencia;
            inValue.Body.tabla = tabla;
            inValue.Body.componente = componente;
            inValue.Body.destino = destino;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            inValue.Body.idafi = idafi;
            return ((SisReference.RecepcionTramaSoap)(this)).Validar_RC42V3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.Validar_RC42V2Response SisReference.RecepcionTramaSoap.Validar_RC42V2(SisReference.Validar_RC42V2Request request)
        {
            return base.Channel.Validar_RC42V2(request);
        }
        
        public string Validar_RC42V2(string sUsuario, string sPassword, string servicio, System.DateTime fecate, string disa, string lote, string numformato, string secuencia, string tabla, string componente, string destino, string V_FLAG_VALIDACION)
        {
            SisReference.Validar_RC42V2Request inValue = new SisReference.Validar_RC42V2Request();
            inValue.Body = new SisReference.Validar_RC42V2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.servicio = servicio;
            inValue.Body.fecate = fecate;
            inValue.Body.disa = disa;
            inValue.Body.lote = lote;
            inValue.Body.numformato = numformato;
            inValue.Body.secuencia = secuencia;
            inValue.Body.tabla = tabla;
            inValue.Body.componente = componente;
            inValue.Body.destino = destino;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            SisReference.Validar_RC42V2Response retVal = ((SisReference.RecepcionTramaSoap)(this)).Validar_RC42V2(inValue);
            return retVal.Body.Validar_RC42V2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.Validar_RC42V2Response> SisReference.RecepcionTramaSoap.Validar_RC42V2Async(SisReference.Validar_RC42V2Request request)
        {
            return base.Channel.Validar_RC42V2Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.Validar_RC42V2Response> Validar_RC42V2Async(string sUsuario, string sPassword, string servicio, System.DateTime fecate, string disa, string lote, string numformato, string secuencia, string tabla, string componente, string destino, string V_FLAG_VALIDACION)
        {
            SisReference.Validar_RC42V2Request inValue = new SisReference.Validar_RC42V2Request();
            inValue.Body = new SisReference.Validar_RC42V2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.servicio = servicio;
            inValue.Body.fecate = fecate;
            inValue.Body.disa = disa;
            inValue.Body.lote = lote;
            inValue.Body.numformato = numformato;
            inValue.Body.secuencia = secuencia;
            inValue.Body.tabla = tabla;
            inValue.Body.componente = componente;
            inValue.Body.destino = destino;
            inValue.Body.V_FLAG_VALIDACION = V_FLAG_VALIDACION;
            return ((SisReference.RecepcionTramaSoap)(this)).Validar_RC42V2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.Consulta_RetroarfsisResponse SisReference.RecepcionTramaSoap.Consulta_Retroarfsis(SisReference.Consulta_RetroarfsisRequest request)
        {
            return base.Channel.Consulta_Retroarfsis(request);
        }
        
        public string Consulta_Retroarfsis(string sUsuario, string sPassword, string opcion)
        {
            SisReference.Consulta_RetroarfsisRequest inValue = new SisReference.Consulta_RetroarfsisRequest();
            inValue.Body = new SisReference.Consulta_RetroarfsisRequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.opcion = opcion;
            SisReference.Consulta_RetroarfsisResponse retVal = ((SisReference.RecepcionTramaSoap)(this)).Consulta_Retroarfsis(inValue);
            return retVal.Body.Consulta_RetroarfsisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.Consulta_RetroarfsisResponse> SisReference.RecepcionTramaSoap.Consulta_RetroarfsisAsync(SisReference.Consulta_RetroarfsisRequest request)
        {
            return base.Channel.Consulta_RetroarfsisAsync(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.Consulta_RetroarfsisResponse> Consulta_RetroarfsisAsync(string sUsuario, string sPassword, string opcion)
        {
            SisReference.Consulta_RetroarfsisRequest inValue = new SisReference.Consulta_RetroarfsisRequest();
            inValue.Body = new SisReference.Consulta_RetroarfsisRequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.opcion = opcion;
            return ((SisReference.RecepcionTramaSoap)(this)).Consulta_RetroarfsisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.VerificaFUADuplicadoV2Response SisReference.RecepcionTramaSoap.VerificaFUADuplicadoV2(SisReference.VerificaFUADuplicadoV2Request request)
        {
            return base.Channel.VerificaFUADuplicadoV2(request);
        }
        
        public string VerificaFUADuplicadoV2(string sUsuario, string sPassword, string Disa, string TipoFormato, string Numero)
        {
            SisReference.VerificaFUADuplicadoV2Request inValue = new SisReference.VerificaFUADuplicadoV2Request();
            inValue.Body = new SisReference.VerificaFUADuplicadoV2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.Disa = Disa;
            inValue.Body.TipoFormato = TipoFormato;
            inValue.Body.Numero = Numero;
            SisReference.VerificaFUADuplicadoV2Response retVal = ((SisReference.RecepcionTramaSoap)(this)).VerificaFUADuplicadoV2(inValue);
            return retVal.Body.VerificaFUADuplicadoV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.VerificaFUADuplicadoV2Response> SisReference.RecepcionTramaSoap.VerificaFUADuplicadoV2Async(SisReference.VerificaFUADuplicadoV2Request request)
        {
            return base.Channel.VerificaFUADuplicadoV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.VerificaFUADuplicadoV2Response> VerificaFUADuplicadoV2Async(string sUsuario, string sPassword, string Disa, string TipoFormato, string Numero)
        {
            SisReference.VerificaFUADuplicadoV2Request inValue = new SisReference.VerificaFUADuplicadoV2Request();
            inValue.Body = new SisReference.VerificaFUADuplicadoV2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.Disa = Disa;
            inValue.Body.TipoFormato = TipoFormato;
            inValue.Body.Numero = Numero;
            return ((SisReference.RecepcionTramaSoap)(this)).VerificaFUADuplicadoV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.BuscarPersonalSaludV3Response SisReference.RecepcionTramaSoap.BuscarPersonalSaludV3(SisReference.BuscarPersonalSaludV3Request request)
        {
            return base.Channel.BuscarPersonalSaludV3(request);
        }
        
        public string BuscarPersonalSaludV3(string sUsuario, string sPassword, string TipoDocumento, string Documento)
        {
            SisReference.BuscarPersonalSaludV3Request inValue = new SisReference.BuscarPersonalSaludV3Request();
            inValue.Body = new SisReference.BuscarPersonalSaludV3RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.TipoDocumento = TipoDocumento;
            inValue.Body.Documento = Documento;
            SisReference.BuscarPersonalSaludV3Response retVal = ((SisReference.RecepcionTramaSoap)(this)).BuscarPersonalSaludV3(inValue);
            return retVal.Body.BuscarPersonalSaludV3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.BuscarPersonalSaludV3Response> SisReference.RecepcionTramaSoap.BuscarPersonalSaludV3Async(SisReference.BuscarPersonalSaludV3Request request)
        {
            return base.Channel.BuscarPersonalSaludV3Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.BuscarPersonalSaludV3Response> BuscarPersonalSaludV3Async(string sUsuario, string sPassword, string TipoDocumento, string Documento)
        {
            SisReference.BuscarPersonalSaludV3Request inValue = new SisReference.BuscarPersonalSaludV3Request();
            inValue.Body = new SisReference.BuscarPersonalSaludV3RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.TipoDocumento = TipoDocumento;
            inValue.Body.Documento = Documento;
            return ((SisReference.RecepcionTramaSoap)(this)).BuscarPersonalSaludV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SisReference.BuscarPersonalSaludV2Response SisReference.RecepcionTramaSoap.BuscarPersonalSaludV2(SisReference.BuscarPersonalSaludV2Request request)
        {
            return base.Channel.BuscarPersonalSaludV2(request);
        }
        
        public string BuscarPersonalSaludV2(string sUsuario, string sPassword, string Documento)
        {
            SisReference.BuscarPersonalSaludV2Request inValue = new SisReference.BuscarPersonalSaludV2Request();
            inValue.Body = new SisReference.BuscarPersonalSaludV2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.Documento = Documento;
            SisReference.BuscarPersonalSaludV2Response retVal = ((SisReference.RecepcionTramaSoap)(this)).BuscarPersonalSaludV2(inValue);
            return retVal.Body.BuscarPersonalSaludV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SisReference.BuscarPersonalSaludV2Response> SisReference.RecepcionTramaSoap.BuscarPersonalSaludV2Async(SisReference.BuscarPersonalSaludV2Request request)
        {
            return base.Channel.BuscarPersonalSaludV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SisReference.BuscarPersonalSaludV2Response> BuscarPersonalSaludV2Async(string sUsuario, string sPassword, string Documento)
        {
            SisReference.BuscarPersonalSaludV2Request inValue = new SisReference.BuscarPersonalSaludV2Request();
            inValue.Body = new SisReference.BuscarPersonalSaludV2RequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sPassword = sPassword;
            inValue.Body.Documento = Documento;
            return ((SisReference.RecepcionTramaSoap)(this)).BuscarPersonalSaludV2Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        new public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecepcionTramaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.RecepcionTramaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RecepcionTramaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://app.sis.gob.pe/EDI/RecepcionTrama.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.RecepcionTramaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://app.sis.gob.pe/EDI/RecepcionTrama.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            RecepcionTramaSoap,
            
            RecepcionTramaSoap12,
        }
    }
}
