USE [SIGH]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[web_crearPacienteV2]
@nRpta int output,
@IdPaciente int=null,
@ApellidoPaterno varchar(40) = null,
@ApellidoMaterno varchar(40) = null,
@PrimerNombre varchar(40) = null,
@SegundoNombre varchar(40) = null,
@TercerNombre varchar(40) = null,
@FechaNacimiento datetime,
@NroDocumento varchar(12) = null,
@Telefono varchar(10) = null,
@DireccionDomicilio varchar(1000) = null,
@Autogenerado varchar(30) = null,
@IdTipoSexo int=null,
@IdProcedencia int=null,
@IdGradoInstruccion int=null,
@IdEstadoCivil int=null,
@IdDocIdentidad int=null,
@IdTipoOcupacion int=null,
@IdCentroPobladoNacimiento int=null,
@IdCentroPobladoDomicilio int=null,
@NombrePadre varchar(20) = null,
@NombreMadre varchar = null,
@NroHistoriaClinica varchar(50)=null,
@IdTipoNumeracion int=null,
@IdCentroPobladoProcedencia int=null,
@Observacion varchar(max) = null,
@IdPaisDomicilio int=null,
@IdPaisProcedencia int=null,
@IdPaisNacimiento int=null,
@IdDistritoProcedencia int=null,
@IdDistritoDomicilio int=null,
@IdDistritoNacimiento int=null,
@FichaFamiliar varchar(20) = null,
@IdEtnia varchar(2) = null,
@GrupoSanguineo varchar(10) = null,
@FactorRh varchar(10) = null,
@UsoWebReniec bit,
@IdIdioma int=null,
@Email varchar(50) = null,
@madreDocumento varchar(12) = null,
@madreApellidoPaterno varchar(20) = null,
@madreApellidoMaterno varchar(20) = null,
@madrePrimerNombre varchar(20) = null,
@madreSegundoNombre varchar(20) = null,
@NroOrdenHijo int=null,
@madreTipoDocumento int=null,
@Sector varchar(2) = null,
@Sectorista int=null,
@EstadoMigracion int=null,
@idReligion int=null,

@IdDepartamentoDomicilio int=null,
@IdDepartamentoProcedencia int=null,
@IdDepartamentoNacimiento int=null,

@Acompaniante varchar(max) = null,
@IdUsuarioAuditoria int = null,

@CipPaciente varchar(20) = null,
@TelefonoMadre varchar(15) = null,
@cboParentescoMadre int = null,
@TipoMPadres int = null,
@NroDocMPadres varchar(15) = null,
@NombresMPadres varchar(100) = null,
@TipoPPadres int = null,
@NroDocPPadres varchar(15) = null,
@NombresPPadres varchar(100) = null,
@ParentescoPaciente int = null,
@cboDiscapacidadPaciente int = null,
@DependenciaPaciente int = null,
@UnidadPagoPaciente int = null,
@GradoPaciente int = null,
@SituacionPaciente int = null,
@FactorRHPaciente varchar(10) = null,
@GrupoSanguineoPaciente varchar(10) = null,
@CodigoCajaPensionPaciente varchar(10) = null,
@Telefono2Paciente varchar(10) = null,
@Telefono3Paciente varchar(10) = null,
@IdPaisMadre int = null,
@idDepartamentoMadre int = null,
@idProvinciaMadre int = null,
@idDistritoMadre int = null,
@idCentroPobladoMadre int = null,
@DireccionMadre varchar(150) = null

AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION;

        IF @IdPaciente = 0
        BEGIN

            DECLARE @IdPacienteGenerado INT

            INSERT INTO Pacientes2207
            (
                ApellidoPaterno,
                ApellidoMaterno,
                PrimerNombre,
                SegundoNombre,
                TercerNombre,
                FechaNacimiento,
                NroDocumento,
                Telefono,
                DireccionDomicilio,
                Autogenerado,
                IdTipoSexo,
                IdProcedencia,
                IdGradoInstruccion,
                IdEstadoCivil,
                IdDocIdentidad,
                IdTipoOcupacion,
                IdCentroPobladoNacimiento,
                IdCentroPobladoDomicilio,
                NombrePadre,
                NombreMadre,
                NroHistoriaClinica,
                IdTipoNumeracion,
                IdCentroPobladoProcedencia,
                Observacion,
                IdPaisDomicilio,
                IdPaisProcedencia,
                IdPaisNacimiento,
                IdDistritoProcedencia,
                IdDistritoDomicilio,
                IdDistritoNacimiento,
                FichaFamiliar,
                IdEtnia,
                GrupoSanguineo,
                FactorRh,
                UsoWebReniec,
                IdIdioma,
                Email,
                madreDocumento,
                madreApellidoPaterno,
                madreApellidoMaterno,
                madrePrimerNombre,
                madreSegundoNombre,
                NroOrdenHijo,
                madreTipoDocumento,
                Sector,
                Sectorista,
                InfIdParentescoTitular,
                Telefono2,
                Telefono3,
                IdDiscapacidad,
                idUnidadPago,
                CodigoCajaPension,
                InfIdParentesco,
                InfTelefono,
                InfDireccion,
                IdPaisDomicilioTutor,
                IdCentroPobladoDomicilioTutor,
                IdDistritoDomicilioTutor,
                DireccionDomicilioTutor,
                TipoDocumentoPadre,
                NroDocumentoPadre,
                NombresPadre,
                TipoDocumentoMadre,
                NroDocumentoMadre,
                NombresMadre,
                CondLaboral
            )
            VALUES
            (
                @ApellidoPaterno,
                @ApellidoMaterno,
                @PrimerNombre,
                @SegundoNombre,
                @TercerNombre,
                @FechaNacimiento,
                @NroDocumento,
                @Telefono,
                @DireccionDomicilio,
                @Autogenerado,
                @IdTipoSexo,
                @IdProcedencia,
                @IdGradoInstruccion,
                @IdEstadoCivil,
                @IdDocIdentidad,
                @IdTipoOcupacion,
                IIF(@IdCentroPobladoNacimiento=0,NULL,@IdCentroPobladoNacimiento),
                IIF(@IdCentroPobladoDomicilio=0,NULL,@IdCentroPobladoDomicilio),
                @NombrePadre,
                @NombreMadre,
                @NroHistoriaClinica,
                @IdTipoNumeracion,
                IIF(@IdCentroPobladoProcedencia=0,NULL,@IdCentroPobladoProcedencia),
                @Observacion,
                IIF(@IdPaisDomicilio=0,NULL,@IdPaisDomicilio),
                IIF(@IdPaisProcedencia=0,NULL,@IdPaisProcedencia),
                IIF(@IdPaisNacimiento=0,NULL,@IdPaisNacimiento),
                IIF(@IdDistritoProcedencia=0,NULL,@IdDistritoProcedencia),
                IIF(@IdDistritoDomicilio=0,NULL,@IdDistritoDomicilio),
                IIF(@IdDistritoNacimiento=0,NULL,@IdDistritoNacimiento),
                @CipPaciente,
                @IdEtnia,
                @FactorRHPaciente,
                @GrupoSanguineoPaciente,
                @UsoWebReniec,
                @IdIdioma,
                @Email,
                @madreDocumento,
                @madreApellidoPaterno,
                @madreApellidoMaterno,
                @madrePrimerNombre,
                @madreSegundoNombre,
                @NroOrdenHijo,
                @madreTipoDocumento,
                @Sector,
                @Sectorista,
                @cboParentescoMadre,
                @Telefono2Paciente,
                @Telefono3Paciente,
                @cboDiscapacidadPaciente,
                @UnidadPagoPaciente,
                @CodigoCajaPensionPaciente,
                @ParentescoPaciente,
                @TelefonoMadre,
                @DireccionMadre,
                @IdPaisMadre,
                @idDistritoMadre,
                @idCentroPobladoMadre,
                @DireccionMadre,
                @TipoMPadres,
                @NroDocMPadres,
                @NombresMPadres,
                @TipoPPadres,
                @NroDocPPadres,
                @NombresPPadres,
                @ParentescoPaciente
            )

            SET @IdPacienteGenerado = SCOPE_IDENTITY()

            INSERT INTO Pacientes
            (
                IdPaciente,
                ApellidoPaterno,
                ApellidoMaterno,
                PrimerNombre,
                SegundoNombre,
                TercerNombre,
                FechaNacimiento,
                NroDocumento,
                Telefono,
                DireccionDomicilio,
                Autogenerado,
                IdTipoSexo,
                IdProcedencia,
                IdGradoInstruccion,
                IdEstadoCivil,
                IdDocIdentidad,
                IdTipoOcupacion,
                IdCentroPobladoNacimiento,
                IdCentroPobladoDomicilio,
                NombrePadre,
                NombreMadre,
                NroHistoriaClinica,
                IdTipoNumeracion,
                IdCentroPobladoProcedencia,
                Observacion,
                IdPaisDomicilio,
                IdPaisProcedencia,
                IdPaisNacimiento,
                IdDistritoProcedencia,
                IdDistritoDomicilio,
                IdDistritoNacimiento,
                FichaFamiliar,
                IdEtnia,
                GrupoSanguineo,
                FactorRh,
                UsoWebReniec,
                IdIdioma,
                Email,
                madreDocumento,
                madreApellidoPaterno,
                madreApellidoMaterno,
                madrePrimerNombre,
                madreSegundoNombre,
                NroOrdenHijo,
                madreTipoDocumento,
                Sector,
                Sectorista,
                EstadoMigracion,
                idReligion,
                Acompaniante,
                IdDepartamentoDomicilio,
                IdDepartamentoProcedencia,
                IdDepartamentoNacimiento,
                CipPaciente,
                TelefonoMadre,
                cboParentescoMadre,
                TipoMPadres,
                NroDocMPadres,
                NombresMPadres,
                TipoPPadres,
                NroDocPPadres,
                NombresPPadres,
                ParentescoPaciente,
                cboDiscapacidadPaciente,
                DependenciaPaciente,
                UnidadPagoPaciente,
                GradoPaciente,
                SituacionPaciente,
                FactorRHPaciente,
                GrupoSanguineoPaciente,
                CodigoCajaPensionPaciente,
                Telefono2Paciente,
                Telefono3Paciente,
                IdPaisMadre,
                idDepartamentoMadre,
                idProvinciaMadre,
                idDistritoMadre,
                idCentroPobladoMadre,
                DireccionMadre,
                telefono2,
                telefono3,
                IdDiscapacidad,
                idUnidadPago,
                CodigoCajaPension,
                InfIdParentesco,
                InfIdParentescoTitular,
                InfTelefono,
                InfDireccion,
                IdPaisDomicilioTutor,
                IdDistritoDomicilioTutor,
                IdCentroPobladoDomicilioTutor,
                DireccionDomicilioTutor,
                TipoDocumentoPadre,
                NroDocumentoPadre,
                NombresPadre,
                TipoDocumentoMadre,
                NroDocumentoMadre,
                NombresMadre,
                CondLaboral
            )
            VALUES
            (
                @IdPacienteGenerado,
                @ApellidoPaterno,
                @ApellidoMaterno,
                @PrimerNombre,
                @SegundoNombre,
                @TercerNombre,
                @FechaNacimiento,
                @NroDocumento,
                @Telefono,
                @DireccionDomicilio,
                @Autogenerado,
                @IdTipoSexo,
                @IdProcedencia,
                @IdGradoInstruccion,
                @IdEstadoCivil,
                @IdDocIdentidad,
                @IdTipoOcupacion,
                IIF(@IdCentroPobladoNacimiento=0,NULL,@IdCentroPobladoNacimiento),
                IIF(@IdCentroPobladoDomicilio=0,NULL,@IdCentroPobladoDomicilio),
                @NombrePadre,
                @NombreMadre,
                @NroHistoriaClinica,
                @IdTipoNumeracion,
                IIF(@IdCentroPobladoProcedencia=0,NULL,@IdCentroPobladoProcedencia),
                @Observacion,
                IIF(@IdPaisDomicilio=0,NULL,@IdPaisDomicilio),
                IIF(@IdPaisProcedencia=0,NULL,@IdPaisProcedencia),
                IIF(@IdPaisNacimiento=0,NULL,@IdPaisNacimiento),
                IIF(@IdDistritoProcedencia=0,NULL,@IdDistritoProcedencia),
                IIF(@IdDistritoDomicilio=0,NULL,@IdDistritoDomicilio),
                IIF(@IdDistritoNacimiento=0,NULL,@IdDistritoNacimiento),
                @CipPaciente,
                @IdEtnia,
                @FactorRHPaciente,
                @GrupoSanguineoPaciente,
                @UsoWebReniec,
                @IdIdioma,
                @Email,
                @madreDocumento,
                @madreApellidoPaterno,
                @madreApellidoMaterno,
                @madrePrimerNombre,
                @madreSegundoNombre,
                @NroOrdenHijo,
                @madreTipoDocumento,
                @Sector,
                @Sectorista,
                @EstadoMigracion,
                @idReligion,
                @Acompaniante,
                @IdDepartamentoDomicilio,
                @IdDepartamentoProcedencia,
                @IdDepartamentoNacimiento,
                @CipPaciente,
                @TelefonoMadre,
                @cboParentescoMadre,
                @TipoMPadres,
                @NroDocMPadres,
                @NombresMPadres,
                @TipoPPadres,
                @NroDocPPadres,
                @NombresPPadres,
                @ParentescoPaciente,
                @cboDiscapacidadPaciente,
                @DependenciaPaciente,
                @UnidadPagoPaciente,
                @GradoPaciente,
                @SituacionPaciente,
                @FactorRHPaciente,
                @GrupoSanguineoPaciente,
                @CodigoCajaPensionPaciente,
                @Telefono2Paciente,
                @Telefono3Paciente,
                @IdPaisMadre,
                @idDepartamentoMadre,
                @idProvinciaMadre,
                @idDistritoMadre,
                @idCentroPobladoMadre,
                @DireccionMadre,
                @Telefono2Paciente,
                @Telefono3Paciente,
                @cboDiscapacidadPaciente,
                @UnidadPagoPaciente,
                @CodigoCajaPensionPaciente,
                @ParentescoPaciente,
                @cboParentescoMadre,
                @TelefonoMadre,
                @DireccionMadre,
                @IdPaisMadre,
                @idDistritoMadre,
                @idCentroPobladoMadre,
                @DireccionMadre,
                @TipoMPadres,
                @NroDocMPadres,
                @NombresMPadres,
                @TipoPPadres,
                @NroDocPPadres,
                @NombresPPadres,
                @ParentescoPaciente
            )

            SET @nRpta = @IdPacienteGenerado

            INSERT INTO HistoriasClinicas
            (
                NroHistoriaClinica,
                FechaCreacion,
                FechaPasoAPasivo,
                IdTipoHistoria,
                IdEstadoHistoria,
                IdPaciente,
                IdTipoNumeracion,
                NroHistoriaClinicaAnterior,
                IdTipoNumeracionAnterior,
                HistoriaSistemaAnterior
            )
            VALUES
            (
                @NroHistoriaClinica,
                GETDATE(),
                NULL,
                1,
                1,
                @nRpta,
                @IdTipoNumeracion,
                NULL,
                NULL,
                NULL
            )

            EXEC AuditoriaAgregarV @IdUsuarioAuditoria, 'A', @NroHistoriaClinica, 'Pacientes', 101, '', @NroHistoriaClinica
        END
        ELSE
        BEGIN
            UPDATE Pacientes2207 SET
                ApellidoPaterno=@ApellidoPaterno,
                ApellidoMaterno=@ApellidoMaterno,
                PrimerNombre=@PrimerNombre,
                SegundoNombre=@SegundoNombre,
                TercerNombre=@TercerNombre,
                FechaNacimiento=@FechaNacimiento,
                NroDocumento=@NroDocumento,
                Telefono=@Telefono,
                DireccionDomicilio=@DireccionDomicilio,
                InfIdParentesco=@ParentescoPaciente,
                FichaFamiliar=@CipPaciente,
                telefono2=@Telefono2Paciente,
                telefono3=@Telefono3Paciente,
                IdDiscapacidad=@cboDiscapacidadPaciente,
                idUnidadPago=@UnidadPagoPaciente,
                CodigoCajaPension=@CodigoCajaPensionPaciente,
                InfIdParentescoTitular=@cboParentescoMadre,
                InfTelefono=@TelefonoMadre,
                InfDireccion=@DireccionMadre,
                TipoDocumentoPadre=@TipoMPadres,
                NroDocumentoPadre=@NroDocMPadres,
                NombresPadre=@NombresMPadres,
                TipoDocumentoMadre=@TipoPPadres,
                NroDocumentoMadre=@NroDocPPadres,
                NombresMadre=@NombresPPadres,
                IdPaisDomicilioTutor=@IdPaisMadre,
                IdDistritoDomicilioTutor=@idDistritoMadre,
                IdCentroPobladoDomicilioTutor=@idCentroPobladoMadre,
                DireccionDomicilioTutor=@DireccionMadre,
                CondLaboral=@ParentescoPaciente
            WHERE IdPaciente=@IdPaciente

            UPDATE Pacientes SET
                ApellidoPaterno=@ApellidoPaterno,
                ApellidoMaterno=@ApellidoMaterno,
                PrimerNombre=@PrimerNombre,
                SegundoNombre=@SegundoNombre,
                TercerNombre=@TercerNombre,
                FechaNacimiento=@FechaNacimiento,
                NroDocumento=@NroDocumento,
                Telefono=@Telefono,
                DireccionDomicilio=@DireccionDomicilio,
                Autogenerado=@Autogenerado,
                IdTipoSexo=@IdTipoSexo,
                IdProcedencia=@IdProcedencia,
                IdGradoInstruccion=@IdGradoInstruccion,
                IdEstadoCivil=@IdEstadoCivil,
                IdDocIdentidad=@IdDocIdentidad,
                IdTipoOcupacion=@IdTipoOcupacion,
                IdCentroPobladoNacimiento=IIF(@IdCentroPobladoNacimiento=0,NULL,@IdCentroPobladoNacimiento),
                IdCentroPobladoDomicilio=@IdCentroPobladoDomicilio,
                NombrePadre=@NombrePadre,
                NombreMadre=@NombreMadre,
                NroHistoriaClinica=@NroHistoriaClinica,
                IdTipoNumeracion=@IdTipoNumeracion,
                IdCentroPobladoProcedencia=IIF(@IdCentroPobladoProcedencia=0,NULL,@IdCentroPobladoProcedencia),
                Observacion=@Observacion,
                IdPaisDomicilio=@IdPaisDomicilio,
                IdPaisProcedencia=IIF(@IdPaisProcedencia=0,NULL,@IdPaisProcedencia),
                IdPaisNacimiento=IIF(@IdPaisNacimiento=0,NULL,@IdPaisNacimiento),
                IdDistritoProcedencia=IIF(@IdDistritoProcedencia=0,NULL,@IdDistritoProcedencia),
                IdDistritoDomicilio=@IdDistritoDomicilio,
                IdDistritoNacimiento=IIF(@IdDistritoNacimiento=0,NULL,@IdDistritoNacimiento),
                FichaFamiliar=@CipPaciente,
                IdEtnia=@IdEtnia,
                GrupoSanguineo=@GrupoSanguineo,
                FactorRh=@FactorRh,
                UsoWebReniec=@UsoWebReniec,
                IdIdioma=@IdIdioma,
                Email=@Email,
                madreDocumento=@madreDocumento,
                madreApellidoPaterno=@madreApellidoPaterno,
                madreApellidoMaterno=@madreApellidoMaterno,
                madrePrimerNombre=@madrePrimerNombre,
                madreSegundoNombre=@madreSegundoNombre,
                NroOrdenHijo=@NroOrdenHijo,
                madreTipoDocumento=@madreTipoDocumento,
                Sector=@Sector,
                Sectorista=@Sectorista,
                EstadoMigracion=@EstadoMigracion,
                idReligion=@idReligion,
                Acompaniante=@Acompaniante,
                IdDepartamentoDomicilio=@IdDepartamentoDomicilio,
                IdDepartamentoProcedencia=@IdDepartamentoProcedencia,
                IdDepartamentoNacimiento=@IdDepartamentoNacimiento,
                CipPaciente=@CipPaciente,
                TelefonoMadre=@TelefonoMadre,
                cboParentescoMadre=@cboParentescoMadre,
                TipoMPadres=@TipoMPadres,
                NroDocMPadres=@NroDocMPadres,
                NombresMPadres=@NombresMPadres,
                TipoPPadres=@TipoPPadres,
                NroDocPPadres=@NroDocPPadres,
                NombresPPadres=@NombresPPadres,
                ParentescoPaciente=@ParentescoPaciente,
                cboDiscapacidadPaciente=@cboDiscapacidadPaciente,
                DependenciaPaciente=@DependenciaPaciente,
                UnidadPagoPaciente=@UnidadPagoPaciente,
                GradoPaciente=@GradoPaciente,
                SituacionPaciente=@SituacionPaciente,
                FactorRHPaciente=@FactorRHPaciente,
                GrupoSanguineoPaciente=@GrupoSanguineoPaciente,
                CodigoCajaPensionPaciente=@CodigoCajaPensionPaciente,
                Telefono2Paciente=@Telefono2Paciente,
                Telefono3Paciente=@Telefono3Paciente,
                IdPaisMadre=@IdPaisMadre,
                idDepartamentoMadre=@idDepartamentoMadre,
                idProvinciaMadre=@idProvinciaMadre,
                idDistritoMadre=@idDistritoMadre,
                idCentroPobladoMadre=@idCentroPobladoMadre,
                DireccionMadre=@DireccionMadre,
                telefono2=@Telefono2Paciente,
                telefono3=@Telefono3Paciente,
                IdDiscapacidad=@cboDiscapacidadPaciente,
                idUnidadPago=@UnidadPagoPaciente,
                CodigoCajaPension=@CodigoCajaPensionPaciente,
                InfIdParentesco=@ParentescoPaciente,
                InfIdParentescoTitular=@cboParentescoMadre,
                InfTelefono=@TelefonoMadre,
                InfDireccion=@DireccionMadre,
                TipoDocumentoPadre=@TipoMPadres,
                NroDocumentoPadre=@NroDocMPadres,
                NombresPadre=@NombresMPadres,
                TipoDocumentoMadre=@TipoPPadres,
                NroDocumentoMadre=@NroDocPPadres,
                NombresMadre=@NombresPPadres,
                IdPaisDomicilioTutor=@IdPaisMadre,
                IdDistritoDomicilioTutor=@idDistritoMadre,
                IdCentroPobladoDomicilioTutor=@idCentroPobladoMadre,
                DireccionDomicilioTutor=@DireccionMadre,
                CondLaboral=@ParentescoPaciente
            WHERE IdPaciente=@IdPaciente

            SET @nRpta = @IdPaciente

            EXEC AuditoriaAgregarV @IdUsuarioAuditoria, 'M', @IdPaciente, 'Pacientes', 101, '', @NroHistoriaClinica
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;

        THROW;
    END CATCH
END
GO